import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const load=async n=>import('data:text/javascript;base64,'+Buffer.from(await readFile(new URL('../static/js/'+n,import.meta.url),'utf8')).toString('base64'));
const {adaptIntelligence,visibleArticles,mapArticles}=await load('news_model.js');
const {presentOutlook,markerPresentation}=await load('news_presentation.js');
const raw={article_id:'outlook',headline:'Microsoft earnings set for Thursday',content_type:'outlook',ticker_analysis:[],event:null,geography:null,feed:{state:'surface'},severity:{level:'N/A — Upcoming'},outlook:{category:'earnings',status:'upcoming',catalysts:[{name:'earnings'}],scheduled_at_utc:null,expected_window:'Thursday',related_tickers:[{ticker:'MSFT',relationship:'direct_catalyst_subject'}],watch_reasons:['Microsoft earnings set for Thursday']}};
const event={article_id:'event',headline:'AWS outage',ticker_analysis:[],feed:{state:'surface'},event:{event_type:'outage'},severity:{level:'Medium'}};
const skip={...raw,article_id:'skip',headline:'Apple TV best shows',content_type:'skip'};
const adapted=adaptIntelligence({schema_version:'news_ui_v3',queue:[],articles:[raw,event,skip]});
assert.deepEqual(visibleArticles(adapted).map(e=>e.id),['event','outlook']);
assert.deepEqual(visibleArticles(adapted,'outlook').map(e=>e.id),['outlook']);
assert.deepEqual(visibleArticles(adapted,'events').map(e=>e.id),['event']);
assert.equal(visibleArticles(adapted,'all').length,2);
const outlook=adapted.find(e=>e.id==='outlook');
assert.deepEqual(outlook.analyses,[]);assert.deepEqual(outlook.affected_tickers,['MSFT']);
assert.deepEqual(mapArticles([outlook]),[]);
assert.equal(markerPresentation(outlook).severity,'N/A — Upcoming');
assert.equal(presentOutlook(outlook).timing,'Thursday / Not precisely resolved');
assert.equal(presentOutlook(outlook).status,'Upcoming');
assert.deepEqual(presentOutlook(outlook).reasons,raw.outlook.watch_reasons);
assert.deepEqual(presentOutlook(outlook).tickers,['MSFT']);
assert.equal(markerPresentation(adapted.find(e=>e.id==='event')).severity,'Medium');
console.log('PASS Outlook model, type filtering, backend-only relationships, timing, severity and geography.');
