import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../static/js/news_model.js',import.meta.url),'utf8');
const {positionValue,adaptIntelligence,hasCoordinates,MARKETS,matchesEvent,ageLabel}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
assert.equal(positionValue('AAPL',215,10).price,null);assert.equal(positionValue('AAPL',215,10).pnl,null);
const quotes={AAPL:228.4},base=positionValue('aapl',215,10,quotes);assert.ok(Math.abs(base.pnl-134)<1e-8);assert.equal(base.basis,2150);
for(const [cost,qty] of [[-1,1],[1,-1],['',1],[1,''],['abc',1],[Infinity,1]])assert.ok(positionValue('AAPL',cost,qty).error);
assert.ok(positionValue('<script>',1,1).error);assert.ok(positionValue('AAPL',1e308,1e308).error);
const load=async name=>JSON.parse(await readFile(new URL('../data/news/research/'+name,import.meta.url),'utf8'));
const contract=x=>({...x,schema_version:'news_ui_v1',queue:x.research_queue});
const live=adaptIntelligence(contract(await load('mag7_live_sample21_run2_legal_fix.json')));
assert.equal(live.length,21);assert.equal(live.filter(a=>a.gate.is_event).length,4);assert.ok(live.every(a=>a.analyses.length===0));
assert.ok(live.every(a=>!hasCoordinates(a)));assert.equal(ageLabel(null),'Unavailable');
const qa=adaptIntelligence(contract(await load('relevance_qa_round2_run2.json')));
assert.equal(qa.find(a=>a.id==='relevance_qa_001').analyses[0].relationship_type,'direct_event_subject');
const nvda=qa.find(a=>a.id==='relevance_qa_002');assert.equal(nvda.analyses[0].relationship_type,'indirect_exposure_match');assert.equal(nvda.analyses[0].materiality.level,'Unknown');assert.equal(nvda.analyses[0].historical_reaction.status,'unavailable');assert.ok(matchesEvent(nvda,'nvda'));
assert.equal(nvda.analyses[0].direction,'Analyst judgment required');
const multi=contract(await load('relevance_qa_round2_run2.json'));multi.articles[1].ticker_analysis.push({...multi.articles[1].ticker_analysis[0],ticker:'TEST_SECOND'});
assert.equal(adaptIntelligence(multi).find(a=>a.id==='relevance_qa_002').analyses.length,2);
assert.deepEqual(adaptIntelligence({schema_version:'news_ui_v1',queue:[],articles:[]}),[]);
assert.throws(()=>adaptIntelligence({articles:[]}));
assert.equal(hasCoordinates({latitude:null,longitude:null}),false);assert.equal(hasCoordinates({latitude:0,longitude:0}),true);assert.equal(hasCoordinates({latitude:91,longitude:0}),false);
assert.ok(MARKETS.every(m=>m[1]===null&&m[2]===null));
console.log('PASS: real articles, no-match/rejected, direct/indirect, multiple tickers, empty/malformed, coordinates, Unknown/unavailable, unmodified direction and no demo quotes.');

const current=await load('news_research_v2_current.json');
const v2=adaptIntelligence({...current,schema_version:'news_ui_v2',queue:current.research_queue});
const commentary=v2.find(a=>a.title.startsWith('Nvidia boss'));
assert.equal(commentary.analyses[0].relevance.level,'High');assert.equal(commentary.severity.level,'Low');assert.notEqual(commentary.category,'rejected');
assert.ok(v2.some(a=>a.analyses.length===0&&hasCoordinates(a)));
const ui=await readFile(new URL('../static/js/news_ui.js',import.meta.url),'utf8');
assert.ok(ui.includes("present(e,t)"));
assert.ok(!ui.includes('Number.isFinite(t.relevance_score)?String(t.relevance_score)'));
console.log('PASS: V2 human relevance, separate severity, unmatched geography, policy-score disclosure.');
