import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const load=async n=>import('data:text/javascript;base64,'+Buffer.from(await readFile(new URL('../static/js/'+n,import.meta.url),'utf8')).toString('base64'));
const {portfolioTotals,portfolioMatches,loadPositions,savePositions,retainedSelection,scoreText,snapshotIdentity}=await load('news_product.js');
const p=[{ticker:'NVDA',shares:10,cost:100}],q={NVDA:{value:120,currency:'USD',status:'delayed'}};
assert.deepEqual(portfolioTotals(p,q),{basis:1000,value:1200,pnl:200,percent:20,missing:0,stale:false});
assert.equal(portfolioTotals(p,{}).value,null);assert.equal(portfolioTotals(p,{NVDA:{...q.NVDA,currency:'HKD'}}).value,null);
assert.equal(portfolioTotals([{ticker:'NVDA',shares:1,cost:0}],q).percent,null);
assert.equal(portfolioTotals(p,{NVDA:{...q.NVDA,status:'stale'}}).stale,true);
assert.deepEqual(portfolioMatches({analyses:[]},p),[]);
assert.deepEqual(portfolioMatches({analyses:[{ticker:'NVDA',qualification:'candidate_requires_review'}]},p),[]);
assert.deepEqual(portfolioMatches({analyses:[{ticker:'NVDA',qualification:'qualified_direct_event_subject'}]},p),['NVDA']);
const storage={value:null,getItem(){return this.value;},setItem(k,v){this.value=v;}};
assert.equal(savePositions(storage,p),true);assert.deepEqual(loadPositions(storage),p);storage.value='bad';assert.deepEqual(loadPositions(storage),[]);
assert.equal(savePositions({setItem(){throw Error();}},p),false);
assert.equal(retainedSelection([{id:'a'}],'a'),'a');assert.equal(retainedSelection([{id:'b'}],'a'),null);
assert.equal(scoreText({level:'High',score:82}),'82.0 / 100 · High');assert.equal(scoreText(null),'Unknown');
assert.equal(snapshotIdentity({generated_at:'x',articles:[],operational:1}),snapshotIdentity({generated_at:'x',articles:[],operational:2}));
console.log('PASS portfolio arithmetic, persistence, qualified-only linkage, polling selection and score semantics.');
